### ISSUE TITLE
[Question] Get the compiled version of the map?

### ISSUE THREAD

**Issue by conradogarciaberrotaran** [DigiWorm0/LevelImposter#5]
Is there a way to get the compiled version of the map? Meaning i don't need to run the injector to get the map running.

Thanks!

**Comment by DigiWorm0** [comment]
I don't quite understand what you mean by "The compiled version". The [LevelImposter editor](https://levelimposter.net/Home/Editor) outputs a JSON representation of the map which is read and parsed by a BepInEx plugin which overrides Among Us's functions and overwrites the Polus. There is no way for one to get a "compiled" version of the map because the JSON file is parsed/compiled at runtime. Even if there was, there are a variety of Among Us methods and functions that are not very flexible to changes in their environment.

If you want to avoid using the exe, you can add the BepInEx plugins manually: 
![image](https://user-images.githubusercontent.com/10067568/116143277-8fa70d00-a6a0-11eb-861b-ed18d289ca97.png)

**Comment by conradogarciaberrotaran** [comment]
Thanks! this is what i was looking for
